### ISSUE TITLE
Image not pointing at an image causing 'Disposed'

### ISSUE THREAD

**Issue by Deathspike** [Deathspike/mangarack.js#11]
It sometimes happens a site lists an image that isn't even an image at all. A ghost page, so to say.

While technically correct, we should probably ignore obviously broken pages.

Thoughts, @Mike43110 @XellossMetallium?

**Comment by Mike43110** [comment]
Excuse the close and reopen. I am very good at pressing close instead of comment.

Those broken pages make CRA sometimes crash, so I would be quite pleased with this change. No longer having to guess what page to jump to!

So +1 on ignoring obviously broken pages.
http://mangafox.me/manga/naruto/v72/c700/29.html
is an example

**Comment by XellossMetallium** [comment]
Never experienced that on Batoto.. and I have just a couple of series on mangafox. So there is no problem during the upload, is just an error on the server side where an additional inexistent page is added without impact on the flow of the story? 
Surely I agree. If the broken pages can even make Comicrack crash, it would be better to cut them out from the beginning.

**Comment by Mike43110** [comment]
It crashes android only.
It does occur on both batoto and kissmanga as well, quite a pain!

It's a server side error so there isn't anything that can be done other than dropping the dead page really.

**Comment by XellossMetallium** [comment]
Oh, ComicRackAndroid, I see.. I missed the meaning of the A even if I use the app myself :smile: 
Well, I'm in the process of moving my entire on-going library to mangarack (I am still at letter O), so for now I'm only reading volumes I compiled myself on android; probably this is why I still haven't experienced yet the crashes.

**Comment by Deathspike** [comment]
It's not exactly the kind of half-back page you've sparsely encountered, @Mike43110. Instead it is all the more related to incorrect implementations of the scanlation site algorithm to index archives. For example, on MangaFox, the pages seem to be indexed based on the maximum number in the archive. if there are pages named 24-25.jpg, for example, then there are not enough pages for the listing, and that would end up in a broken reader state. That's basically what I am fixing here.
