### ISSUE TITLE
Suggestion: error log file and error skipping during the download process.

### ISSUE THREAD

**Issue by XellossMetallium** [Deathspike/mangarack.js#12]
Today mangarack gave me an error regarding Grisaia no Kaijutsu on Batoto. Pasting the link in the browser I found out that it changed from this http://bato.to/comic/_/comics/grisaia-no-kajitsu-r8532 to this: http://bato.to/comic/_/comics/grisaia-no-kajitsu-sanctuary-fellows-r8532. 
Now, the redirect on the site is automatic, but mangarack simply treat it as missing. 
Indeed, a manual correction is needed since the download folder changes with the title, but in this particular case couldn't mangarack be made aware of the redirect and report in an apposit log file the manteinance needed? This could be expanded to every case there is an error (specifying when possible what kind of error) without interrupting every time the process (which is a major point for me since I usually download during night).

It should be off topic, butI take the chance to ask.. precisely what does this option do?
-p or --persistent disables persistent tracking and renaming.

**Comment by Deathspike** [comment]
I'll add support for redirect to mediate this issue.

Error logging into a separate file is actually quite a hurdle with the current architecture. To elaborate just a little; I've set up MangaRack.js to be capable of running in several forms, one of which is the CLI application you're using now. Another form of usage is in your own application as a library, on a web application, on a desktop application and even on a phone. The latter options are all future considerations. Adding a separate error logging is simply not possible without overhauling the entire architecture. I think you can imagine I have no interest in doing that at this moment.

Interrupting the process is actually part of the aforementioned design. However, it wouldn't be that much of a stretch to add a CLI option which ignores errors and keeps going with the remaining tasks (for example, `-k, --keep-alive`). I'm going to split this off to #13.

Persistent disabling prevents writing the `.mrpersist` file. It allows for renaming and prevents re-downloads after you've moved the files.

**Comment by XellossMetallium** [comment]
I see, I didn't imagined these kind of problems could emerge! I understand your point perfectly!
