### ISSUE TITLE
Bug - "No chapter" error on certian series.

### ISSUE THREAD

**Issue by XellossMetallium** [Deathspike/mangarack.js#14]
I experienced this error from time to time, but usually once I've restarted the process it all goes well (maybe something related to connection timeout?). Yet for certian series  the error is persistent and forced me to obscure their links so that the process could continue smoothly. Now that we have the --keep-alive option I tried a separate process with only the problematic links in the list and I noticed that some chapters, but never all of them (looks quite random) are actually downloaded each time I start the .bat, yet in 4-5 runs the process still gives mixed results, like errors or isolate chapters correctly downloaded. 
The links appear to be correct and the chapters not downloaded by mangarack looks fine on batoto (I tried some at random).

Right now the problematic series I encountered should be the following:
B
http://bato.to/comic/_/comics/btooom-r899
G
http://bato.to/comic/_/comics/gokukoku-no-brynhildr-r3594
http://bato.to/comic/_/comics/gurenki-creo-the-crimson-crises-r6840
M
http://bato.to/comic/_/comics/mahouka-koukou-no-rettousei-r3290
N
http://bato.to/comic/_/comics/nyan-koi-r509

and a screenshot of the error:
![screenshot 2015-01-02 15 00 10](https://cloud.githubusercontent.com/assets/6177535/5596607/13b7f920-9293-11e4-8b5a-18db48302828.png)

Right now:
Btooom: only v3 c17 downloaded
Gokukoku no brynhildr: each run it downloads from 3 to 5 chapters (in order), then "No Chapter".
Gurenki: in more tries it was downloaded all, except omake and ch10, no luck with them.
Mahouka: only a single chapter downloaded (ch3)
Nyan Koi: no chapter ever downloaded.

Sorry if I missed something.

**Comment by Deathspike** [comment]
Great find! I didn't encounter it yet. I'm confident I fixed it. Please check and comment :+1:

**Comment by XellossMetallium** [comment]
It went well with the "bugged.bat" that I prepared for testing purposes with all problematic mangas, so I stopped the downloads and started the proper library global update. Now is going fine past ch15 of Gokukoku, so I think we can consider this solved :)

**Comment by XellossMetallium** [comment]
Maybe this deserve a different issue, but since it happened now for the first time after the update and only affects (it seems) one of the manga that presented the bug of #14 I reopen this.
For Nyan Koi chapters up to 11 were downloaded and now a different error appears, the following:
![screenshot 2015-01-03 01 14 01](https://cloud.githubusercontent.com/assets/6177535/5600925/bb520682-92e6-11e4-949c-0625ee57b289.png)

**Comment by Deathspike** [comment]
This happens when the `.mrpersistent` has become corrupted, for some reason. An error happens when the file is written and goes wrong. I thought I fixed this from ever happening again in 3.0.13. Could it be possible you still have old persistent files around from the 3.0.13 time? If so, simply delete the persistent file with a problem and a new one should be made that cannot go wrong anymore.

**Comment by XellossMetallium** [comment]
Yes, you are right! no problem now :) Thanks
