### ISSUE TITLE
throw err: Cannot find module 'adm-zip'

### ISSUE THREAD

**Issue by damidget** [Deathspike/mangarack.js#15]
I recently decided to transfer from the old MangaRack to the *.js version.
It's been going fine until recently when this occured. Any idea why & how I can fix it?

```
E:\Manga & Comics\Files\Archive - ComicRack; MANGA>call npm update -g mangarack


E:\Manga & Comics\Files\Archive - ComicRack; MANGA>call C:\Users\MattR\AppData\R
oaming\npm\mangarack

module.js:340
    throw err;
          ^
Error: Cannot find module 'adm-zip'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\MattR\AppData\Roaming\npm\node_modules\manga
rack\lib\nodejs\index.js:3:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

E:\Manga & Comics\Files\Archive - ComicRack; MANGA>pause
Press any key to continue . . .
```

**Comment by Deathspike** [comment]
I have no idea why this would happen, unless you interrupt the `npm install -g mangarack` command. Since you've already been using `mangarack`, that seems rather unlikely. First, let us get some information from your system. Please run the following command and comment with the output:

    npm -g list --depth 1

The expected output is something like this:

    └─┬ mangarack@3.1.0
      ├── adm-zip@0.4.4
      ├── archiver@0.13.0
      ├── cheerio@0.18.0
      ├── commander@2.6.0
      ├── gm@1.17.0
      └── xml2js@0.4.4

If these are all listed, the dependencies have been installed and there is no reason why this error should happen in the first place. If the output isn't quite as expected, move on with a re-installation of `mangarack` with the following commands:

    npm uninstall -g mangarack
    npm install -g mangarack

This will force a full re-installation of `mangarack`. Run the `npm -g list --depth 1` again and check the output. Does it have `adm-zip` listed now?

**Comment by damidget** [comment]
yeah, its exactly how you expected it to output, without the adm-zip listed correctly.
```
└─┬ mangarack@3.1.2
  ├── UNMET DEPENDENCY adm-zip@^0.4.4
  ├── archiver@0.13.0
  ├── cheerio@0.18.0
  ├── commander@2.6.0
  ├── gm@1.17.0
  └── xml2js@0.4.4

npm ERR! missing: adm-zip@^0.4.4, required by mangarack@3.1.2
npm ERR! not ok code 0
```
I've uninstalled & reinstalled it now and it's working a charm!

I must add here a bit of praise, this version of MangaRack (*.js) appears to multi-task better than the previous one (*.cs). Downloading a large quantity of new manga appears to occur much faster.
Cheers for producing this little program, Deathspike! :smile:

**Comment by damidget** [comment]
Just another quick question: Is it easy to implement this so I can have it in my taskbar (as an application, I assume) on Windows?

**Comment by Deathspike** [comment]
Thank you for the praise! A lot of effort went into optimizing the concurrency works, faster image processing, and a task-runner that distributes load across all available workers regardless if it's one series. Glad your problem is solved.

To answer your question I need some more information, what do you mean 'as an application'? I see that you are using the `.bat` file from the Windows extras, so you should already have an application window for the `mangarack` console, unless you mean something different?

**Comment by damidget** [comment]
If I try to add the bat file to the quick launch toolbar on the taskbar (traditionally bottom left, next to the windows start-menu), it saves the shortcut as 'command prompt' to the icons. This means when I double-click the icon in the taskbar, it opens up the standard command prompt window. This does not start up mangarack.
For example, if you want to quickly access an ordinary application, like Internet Explorer, you can simply drag the *.exe/shortcut into the taskbar. This makes it accessible the whole time you are doing anything on your computer. Unlike desktop shortcuts, where you have to goto the desktop to access them.
Since pictures speak a thousand words: http://support.microsoft.com/kb/975784
Hope that makes sense.

**Comment by Deathspike** [comment]
This is actually quite simple to accomplish. Create a shortcut :-)

1. Right-click in a folder, select `New` and select `Shortcut`.
2. Type in `mangarack` as location of the item.
3. Type in a name for the shortcut as you desire.
4. Now right-click the shortcut and select `Properties.
5. Change the `Start in:` path to your manga folder.

Now double click the shortcut and pin it to the task bar. It will work next time you click it, too.

**Comment by damidget** [comment]
A Shortcut doesn't work for me (Already tried that). I don't know if it's because of something I've done or not though (I've done the exact steps you did and I get the same result). oh well, only a small thing. :)

**Comment by Deathspike** [comment]
An executable is now included in the Windows extras. Hope you like it! Source code:

    using System;
    using System.Diagnostics;
    using System.Threading.Tasks;

    namespace MangaRack
    {
        public class Program
        {
            public static void Main(string[] args)
            {
                var command = "call npm update -g mangarack &&" +
                              "call %AppData%\\npm\\mangarack " +
                              string.Join(" ", args);

                var processInfo = new ProcessStartInfo("cmd.exe", "/c " + command)
                {
                    RedirectStandardError = true,
                    RedirectStandardOutput = true,
                    UseShellExecute = false
                };

                var process = Process.Start(processInfo);
                Task.Factory.StartNew(() => process.StandardError.BaseStream.CopyTo(Console.OpenStandardError()));
                Task.Factory.StartNew(() => process.StandardOutput.BaseStream.CopyTo(Console.OpenStandardOutput()));
                process.WaitForExit();

                Console.WriteLine("Press [ENTER] to exit.");
                Console.ReadLine();
            }
        }
    }

**Comment by damidget** [comment]
LEGEND! Working beautifully! :)
