### ISSUE TITLE
Invalid characters error.

### ISSUE THREAD

**Issue by XellossMetallium** [Deathspike/mangarack.js#17]
Exemple: Again - Chapter 91. 
Possibly caused by the star symbol and another one I cannot recognize in the title? As always, Windows 7 64.

![screenshot 2015-01-17 08 00 16](https://cloud.githubusercontent.com/assets/6177535/5789514/487f5464-9e6e-11e4-9b1a-dee10652ad07.png)

**Comment by Deathspike** [comment]
I'll be assuming it is http://bato.to/comic/_/comics/again-r3749

**Comment by XellossMetallium** [comment]
Yes, sorry, I forgot to link it!

**Comment by Deathspike** [comment]
This will be released in the next patch.
