### ISSUE TITLE
Disposed (Horimiya V4 C27) - Batoto.

### ISSUE THREAD

**Issue by XellossMetallium** [Deathspike/mangarack.js#18]
As the title says, there is no error log (just "fetching" an then "disposed") and no trace left (no .mrdownload file left as in the "invalid character" error). Nor I can find any strangeness in the title or in the capter itself in batoto. There are two chapters 27 uploaded, so I don't know which of the two Mangarack tries to download.
I wonder if this is related to #11 but since I didn't experience that issue at the time I can't say for sure.

Link: http://bato.to/comic/_/comics/horimiya-r6770

**Comment by Deathspike** [comment]
This will be released in the next patch.
