### ISSUE TITLE
Make option flags enable features instead of disabling

### ISSUE THREAD

**Issue by warmwaffles** [Deathspike/mangarack.js#21]
It feels weird that I have to `mangarack -g -j` to stop genralization and jacket generation. It's more surprising that it is enabled by default. I would have assumed it would enable those features.

I think these options should be opt-in as opposed to opt-out and possibly add in `--no-meta` if you really want it to be enabled by default.

**Comment by Deathspike** [comment]
These features and settings originate from the roots of MangaRack; supporting a comfortable environment to read with ComicRack-enabled devices. The default settings are all tailored towards that endeavour. I am aware that it is quite likely that more and more people are using MangaRack without it being in combination, and the default settings might not make sense for that group. These settings would all have to be disabled to make sense for that latter group:

      -j, --jacket         Disable the comic book jacket/cover.
      -g, --generalize     Disable image generalization.
      -m, --meta           Disable metadata.

I'm very reluctant to do this. While the second group of people might find this more comfortable, the first group will not. This also applies to image processing, especially if you consider the differences between the more casual reader (the ones that use MangaFox and image processing to get complete series relatively quickly) and the more quality-obsessed reader (using Batoto and other high quality sources, and often putting in effort to find missing chapters elsewhere).

The default settings are therefore extremely unlike to change (unless there is some kind of killer argument supporting the change). It's actually quite easy to create a batch or shell script that applies these settings; the Windows example is under `extras` and can be easily modified to include `-jgm` for its batch-mode processing. I don't have a Linux example, but if that's preferred I can make one :-)

**Comment by warmwaffles** [comment]
I got node working just fine on windows and mac so it's not a problem on my end.

I am more used to the command line and enabling things via flags or explicitly disabling them via `--no-meta`, `--no-generalize`. Guess I can get used to it :wink:
