### ISSUE TITLE
Does not support chapters labeled as "Ep" instead of "Ch"

### ISSUE THREAD

**Issue by benbarclay** [Deathspike/mangarack.js#27]
See http://kissmanga.com/Manga/Magical-Exam-Student for an example of where chapters are marked as episodes.

By changing line 11 in lib/shared/scanner.js from "Ch" to "Ep" in the regex, I was able to work around this.

Not confident enough to modify that regexp without breaking something though.

**Comment by Deathspike** [comment]
Released in 3.1.6
