### ISSUE TITLE
Question: Mangarack on NAS (Synology)

### ISSUE THREAD

**Issue by XellossMetallium** [Deathspike/mangarack.js#30]
Hi!
A couple of days ago I got this nice and economic Nas, Synology DS115j, to give some peace to my pc. 
My knowledge is limited as always, so before elaborating further, should it be possible to install Mangarack on it?
Thanks!

**Comment by Deathspike** [comment]
Yes and no.

Yes, it is possible to open a terminal session to a Synology device. These devices run a Linux flavor and it is theoretically possible to connect through a SSH session to them. This will enable you to install software onto the device; you will need nodejs (according to Google, you'd have to compile it yourself) and graphicksmagick. Once you've got them, you can `npm install mangarack` and run `mangarack` from the SSH terminal.

No, you will not have nice GUI integration with MangaRack. Of course, take this advice with a grain of salt. I have very little experience with Synology devices, but MangaRack was written to run on any nodejs-capable device and we have instructions to run it on the most popular ones, but I am by no means an expert in all Linux-specific devices.

I hope this helps at least a little :-)

**Comment by XellossMetallium** [comment]
It does indeed! 
I tried to do what I could. 
Luckly nodejs is provided as a package, so that part was easy. 
Then I got to the SSH part. Using a sw called "putty" and editing a certain "passwd" file to give my user access to SSH (at first only the admin and root user could), I was able to open a session. 
I managed to install graphicsmagik without issue.
To install mangarack I had an issue, probably related to permissions (?), since logging in with root allowed me to install it just fine. 
I even tried with a basic command (download this manga in this folder) and it works.

Now, about the GUI thing, to what extent it will not be available? Taking for instance my configuration on windows (like reported in #23 post 2) to what extent would I be able to achieve something similar? 
Thanks again!

**Comment by Deathspike** [comment]
Running it like this:

`mangarack --source SomeInputFile.txt &`

Should attach a command line process to a background process (i.e. not block the terminal). Running things in serial should be easier, though, and probably less taxing on the device. MangaRack itself is really quite the dumb little program; it does exactly as you specify it to do. I don't know the `nohub` command, but if it changes the work directory then yes, that is expected (--output can override work directory for output :+1: )

**Comment by XellossMetallium** [comment]
Sorry for the wait, exams... I've made some tries and it seems to work fine, the only thing I can't figure out is why it "duplicates the folders". 
Anyway, all things considered the Nas is too slow when compared to a desktop machine, it is not worth the effort. Better to mirror the download folder to the Nas drive to have it shared when the desktop is offline :) 
For now I close this issue, thanks! :)
