### ISSUE TITLE
Error: No series

### ISSUE THREAD

**Issue by XellossMetallium** [Deathspike/mangarack.js#32]
Hi, I just switched to windows 10 preview to try it out and now I experience this error each time I run my command. 
A bit of background: on windows 7 sometimes this error occurred, but quite randomly (or at least it was something similar: https://www.dropbox.com/s/ycxy7s3kwdknytv/Screenshot%202015-04-11%2014.16.49.png?dl=0 ) .. should I say when.. when I opened batoto on my browser when mangarack was running. 
What is different now with windows 10 is that mangarack correctly execute the first 3 commands (list 1, which is Batoto "numeric" titles, kissmanga list and mangafox list.. but when it comes to the bigger lists it is as you can see in the screenshot. 
This is the actual error on windows 10:
https://www.dropbox.com/s/0nhh4jweq87lzw6/Screenshot%202015-07-15%2022.52.58.png?dl=0

**Comment by Deathspike** [comment]
I doubt this is Windows 10 specific, but I can't read the series links very well.

Can you post them for me to look at? If I can't reproduce it, I'll get W10 in a VM on the 29th :)

**Comment by XellossMetallium** [comment]
I see! :)
Well, here a (batoto) list that works:
https://dl.dropboxusercontent.com/u/37448634/%23.txt
and there two (batoto) lists that didn't work:
https://dl.dropboxusercontent.com/u/37448634/%7EBatotoNonJap.txt
https://dl.dropboxusercontent.com/u/37448634/A.txt

By the way, when I experienced the "no series" error on windows 7 it happened when I opened batoto on chrome, so even in the middle of the scanning (some titles were "surveyed" correctly, then the error.. restarting the process would usually solve the issue).
Now the error happens at the start of each list, both when I run them sequentially with a single batch or one by one. Except for the non-batoto ones and the one linked above (#.txt), that seems to work each time.

**Comment by XellossMetallium** [comment]
Update, referring to #10 : 
And by the way it seems that a list with 1 to 5 names gives no "no series" #32 error, while with more titles not only I have the issue, but a following list, while having less than 5 entries (in my case the Z list), still fails, like a sort of temporary ban, maybe?

**Comment by XellossMetallium** [comment]
Ok, now this is a problem: I reverted back to good old Windows 7 (x64) and reinstalling Mangarack the error persists.
Just to be sure, I installed the following:
node-v0.12.7-x64.msi
GraphicsMagick-1.3.21-Q8-win64-dll.exe (I tried Q16 too)

then I used the "installer" bat provided by you.

Then I tried using the x86 versions, but nothing.

The only thing I noticed is that trying to install mangarack with the command "npm install -g mangarack" gives the following warning:

![screenshot 2015-07-27 10 46 11](https://cloud.githubusercontent.com/assets/6177535/8901930/2d0977da-344d-11e5-827e-1dfbd67cbdde.png)

**Comment by XellossMetallium** [comment]
I'll leave also this log here (npm-debug.log), other errors maybe related to the setup process:


0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'test' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose config Skipping project config: C:\Users\Mario/.npmrc. (matches userconfig)
5 verbose stack Error: ENOENT, open 'C:\Users\Mario\package.json'
5 verbose stack     at Error (native)
6 verbose cwd C:\Users\Mario
7 error Windows_NT 6.1.7601
8 error argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "test"
9 error node v0.12.7
10 error npm  v2.11.3
11 error path C:\Users\Mario\package.json
12 error code ENOENT
13 error errno -4058
14 error enoent ENOENT, open 'C:\Users\Mario\package.json'
14 error enoent This is most likely not a problem with npm itself
14 error enoent and is related to npm not being able to find a file.
15 verbose exit [ -4058, true ]

**Comment by Deathspike** [comment]
I can't reproduce this at all. I have a WIndows 10 VM running `node` 0.12.7 and `npm` 2.11.3 with no issue whatsoever. My own machine is still running Windows 8.1, and I just updated `node` and `npm` and re-installed `mangarack`. It still does not show any kind of error.

Would you be up to for some debugging @XellossMetallium? If so, please add me on Skype (r.h.g.v.uden) so we can talk and sort out this problem on your machine(s). It might be related to the location we're in, whether or not we're behind a proxy, or a faulty ISP, for example. At this point, I have no real clue.

**Comment by Deathspike** [comment]
This has been tracked down to a number of maximum parallel requests causing Batoto to start refusing them. I'm guessing this is some kind of anti-flood mechanism, which makes perfect sense. I wasn't getting this particular issue due to the limited number of default works I have (4), whereas @XellossMetallium was getting up to 8. I'll leave the final comments (?) and closing to him. :+1:

**Comment by XellossMetallium** [comment]
I can confirm: this night I've run all the processes at least a couple of times with "--workers 4" flawlessy. 
The maximum number of requests seems to be around five, since the very moment I start messing around on Batoto on chrome the ongoing task fails with the aforementioned error.
Now I'm like a month behind, I suppose we canclose this.
Thank you very much!
