### ISSUE TITLE
Unable to Run?

### ISSUE THREAD

**Issue by trevjames** [Deathspike/mangarack.js#35]
I'm sorry in advance for being a complete beginner, and I apologize if this is the wrong area to be asking for help, however I can't seem to get mangarack to run on Mac OS X. Node, NPM, and GraphicsMagick seem to all be installed correctly (confirmed via Terminal), and running the npm installer for mangarack produces: 

/usr/local/bin/mangarack -> /usr/local/lib/node_modules/mangarack/bin/mangarack
/usr/local/lib
└── mangarack@3.1.8 

However, attempting to run the --help via "mangarack --help" produces the following: 

env: node\r: No such file or directory

My $PATH seems to be set correctly: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin, and I've searched online but can't seem to find a solution. Any ideas?

Thanks in advance!

**Comment by Deathspike** [comment]
Ah, thanks for the report.

This happened before and is due to the way mangarack was published to npm..

I fixed it! Run `npm -g update mangarack` to update and try again :+1:

**Comment by Deathspike** [comment]
Since there has been no further response, closed.

**Comment by trevjames** [comment]
Works perfectly. Thanks!
